# Generated by Django 4.1.1 on 2022-10-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_olimp_tags_alter_olimp_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('SecondName', models.CharField(max_length=100)),
                ('Fomka', models.IntegerField()),
                ('Olympics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.olimp')),
            ],
        ),
    ]
