# Generated by Django 4.1.1 on 2022-10-31 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_trier_fomka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olimp_Trier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Olimp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.olimp')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.trier')),
            ],
        ),
    ]
