# Generated by Django 4.1.1 on 2022-11-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_olimp_trier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olimp_trier',
            name='Olimp',
        ),
        migrations.RemoveField(
            model_name='olimp_trier',
            name='User',
        ),
        migrations.AddField(
            model_name='olimp_trier',
            name='Olimp',
            field=models.ManyToManyField(to='feed.olimp'),
        ),
        migrations.AddField(
            model_name='olimp_trier',
            name='User',
            field=models.ManyToManyField(to='feed.trier'),
        ),
    ]
