# Generated by Django 4.1.1 on 2022-11-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_remove_olimp_trier_olimp_remove_olimp_trier_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trier',
            old_name='Olympics',
            new_name='Olympics1',
        ),
    ]
