# Generated by Django 4.1.1 on 2022-09-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olimp',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='olimp',
            name='Site',
            field=models.URLField(blank=True),
        ),
    ]
